name = "nep-astro"
main = "./.vercel/output/static/_worker.js"
compatibility_date = "2024-11-01"

# For Next.js on Cloudflare Pages using @cloudflare/next-on-pages
[vars]
# Add any runtime environment variables here, e.g.
# API_BASE = "https://api.example.com"

[site]
bucket = ".vercel/output/static"

# Enable durable features if later required
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
