export const exampleBhavaData = {
  bhavas: {
    1: {
      rashi: "MESH",
      grahas: ["SUN", "MERCURY"],
      owner: "MARS",
      qualities: ["Movable", "Masculine"],
      aspectedBy: ["JUPITER", "SATURN"],
    },
    2: {
      rashi: "VRISHABH",
      grahas: ["MOON"],
      owner: "VENUS",
      qualities: ["Fixed", "Feminine"],
      aspectedBy: ["MARS"],
    },
    3: {
      rashi: "MITHUN",
      grahas: [],
      owner: "MERCURY",
      qualities: ["Movable", "Masculine"],
      aspectedBy: [],
    },
    4: {
      rashi: "KARK",
      grahas: ["VENUS"],
      owner: "MOON",
      qualities: ["Movable", "Feminine"],
      aspectedBy: ["SATURN"],
    },
    5: {
      rashi: "SINGH",
      grahas: ["MARS"],
      owner: "SUN",
      qualities: ["Fixed", "Masculine"],
      aspectedBy: [],
    },
    6: {
      rashi: "KANYA",
      grahas: [],
      owner: "MERCURY",
      qualities: ["Movable", "Feminine"],
      aspectedBy: ["SUN"],
    },
    7: {
      rashi: "TULA",
      grahas: ["JUPITER"],
      owner: "VENUS",
      qualities: ["Cardinal", "Masculine"],
      aspectedBy: [],
    },
    8: {
      rashi: "VRISHCHIK",
      grahas: [],
      owner: "MARS",
      qualities: ["Fixed", "Feminine"],
      aspectedBy: ["MERCURY"],
    },
    9: {
      rashi: "DHANU",
      grahas: ["SATURN"],
      owner: "JUPITER",
      qualities: ["Movable", "Masculine"],
      aspectedBy: [],
    },
    10: {
      rashi: "MAKAR",
      grahas: [],
      owner: "SATURN",
      qualities: ["Cardinal", "Feminine"],
      aspectedBy: ["MOON"],
    },
    11: {
      rashi: "KUMBH",
      grahas: [],
      owner: "SATURN",
      qualities: ["Movable", "Masculine"],
      aspectedBy: [],
    },
    12: {
      rashi: "MEEN",
      grahas: ["RAHU"],
      owner: "JUPITER",
      qualities: ["Movable", "Feminine"],
      aspectedBy: ["VENUS"],
    },
  },
};
